version: "3"

services:
  app:
    container_name: "xtcloud"
    image: "paolocremonese/wf-9.0.2.final:xtcloud"
    environment:
      - WILDFLY_USER=admin
      - WILDFLY_PASS=cremonese
      - DB_NAME=telecloud
      - DB_USER=adminjrSz1hq
      - DB_PASS=uQx2ENIP471r
      - DB_URI=db:3306
      - OPENSHIFT_REPO_DIR=/opt/jboss/wildfly/standalone/lib/ext/
      - OPENSHIFT_MYSQL_DATASOURCE=telecloudDatasource
      - MYSQL_TCP_ADDR=172.20.0.2
      - MYSQL_TCP_PORT=3306
    depends_on:
      - db
    volumes:
      - /home/teledata/xtcloud-proxy/TeleCLOUD/xtcloud/userconfig/:/opt/jboss/userconfig/       # persistent data storage for user.config
      - /home/teledata/xtcloud-proxy/TeleCLOUD/xtcloud/clouddata/:/opt/jboss/installer/         # persistent data storage for TeleCloud-OFFLINE
      - /home/teledata/xtcloud-proxy/TeleCLOUD/xtcloud/well-known/:/opt/jboss/.well-known/      # persistent data storage for .well-known (ACME key process)
    ports:
      - "127.0.0.1:8080:8080" # application
      - "127.0.0.1:8443:8443" # application SSL HTTPS
      - "127.0.0.1:9990:9990" # admin console
    networks:
      scloud-net: 
        ipv4_address: 172.20.0.3
        
        
  db:
    container_name: "db-prelive"
    image: "mysql:5.7"
    environment:
      - MYSQL_DATABASE=telecloud
      - MYSQL_USER=adminjrSz1hq
      - MYSQL_PASSWORD=uQx2ENIP471r
      - MYSQL_ROOT_PASSWORD=root
    volumes:
#      - ./workdir/db/init/:/docker-entrypoint-initdb.d/ # init database
      - /home/teledata/xtcloud-proxy/TeleCLOUD/xtcloud/mysqldata/:/var/lib/mysql/              # data storage
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      scloud-net: 
        ipv4_address: 172.20.0.2

  backup:
    container_name: "pl-backup"
    image: databack/mysql-backup
    restart: always
    user: "0"
    volumes:
      - /home/teledata/xtcloud-proxy/TeleCLOUD/xtcloud/mysqlbkp/:/db/                          # database BACKUP
      - /home/teledata/xtcloud-proxy/TeleCLOUD/xtcloud/scripts.d/pre-backup/:/scripts.d/pre-backup/             # PREBACKUP script
      - /home/teledata/xtcloud-proxy/TeleCLOUD/xtcloud/scripts.d/post-backup/:/scripts.d/post-backup/           # POSTBACKUP script
    environment:
#      - DB_DUMP_TARGET=" /db smb://193.100.100.204/Sharing/disk1/TeleCLOUD/scloud "  # ATTENZIONE, è necessario uno spazio dopo il primo doppio apice e prima del d.a. finale !!!!!
      - DB_DUMP_TARGET=/db
      - SMB_USER=cremonese
      - SMB_PASS=Teledata011
      - DB_USER=adminAgPVh9q
      - DB_PASS=8fRB2AWC92Mi
      - DB_DUMP_BEGIN=0808                    # WARNING .. USE GMT TIME !!!
      - DB_SERVER=db
      - DB_DUMP_DEBUG=true
      - DB_DUMP_SAFECHARS=true
    depends_on:
      - db
      - app    
    networks:
      scloud-net: 
        ipv4_address: 172.20.0.4

  reverse:
    container_name: reverse
    hostname: reverse
    image: paolocremonese/nginx:proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - WILDFLY_URL=172.20.0.3
      - WILDFLY_HTTP_PORT=8080
      - WILDFLY_HTTPS_PORT=8443
    volumes:
#      - //home/teledata/scloud-proxy/TeleCLOUD/prelive/nginx/conf:/etc/nginx                  # Configurazione NGINX
      - /home/teledata/xtcloud-proxy/TeleCLOUD/xtcloud/nginx/certificati:/etc/ssl/private      # Certificati SSL
    depends_on:
      - app    
    networks:
      scloud-net: 
        ipv4_address: 172.20.0.5
    
    

#networks:
#    default:
#        driver: bridge
   
networks:
  scloud-net: 
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
        
